TIPOS_ALERGENOS = [
    (1, 'Gluten'),
    (2, 'Crustáceos'),
    (3, 'Huevos'),
    (4, 'Pescado'),
    (5, 'Cacahuetes'),
    (6, 'Soja'),
    (7, 'Lácteos'),
    (8, 'Frutos de cáscara'),
    (9, 'Apio'),
    (10, 'Mostaza'),
    (11, 'Granos de sésamo'),
    (12, 'Dióxido de azufre y sulfitos'),
    (13, 'Moluscos'),
    (14, 'Altramuces'),
]

DESC_ALERGENOS = [
    'Trigo, centeno, cebada y avena, además de otros elaborados con harinas, pastas, bollería, salsas, sopas, etc.',
    'Incluye cangrejos, langostas, gambas, cigalas, etc Además de productos a base de estos crustáceos.',
    'Además de en el huevo y derivados, se puede encontrar en tartas, productos cárnicos, mayonesas, mousses, pastas, platos preparados, salsas, bollería y galletas, etc.',
    'Además de en el pescado y derivados se puede encontrar en salsas de pescado, gelatinas, pizzas, aliños para ensaladas, cubos de sopa, etc.',
    'Incluye los tallos, hojas, semillas y raíces. Además, se pueden encontrar en sal de apio, ensaladas, algunos productos cárnicos, sopas, salsas, etc.',
    'Además de en las semillas, salsas de soja, pastas, aceites y harinas, se pueden encontrar en tofu, pasta miso, postres, helados, productos cárnicos, platos preparados, aliños de ensalada, etc.',
    'Además de en la leche y sus derivados como queso, mantequilla, nata, etc, se puede encontrar en alimentos glaseados con leche, sopas en polvo y salsas, embutidos, bollería, etc.',
    'Incluye almendras, avellanas, nueces, anacardos, etc. Se puede encontrar en bollería, productos a base de frutos secos, en platos especiados, etc',
    'Incluye los tallos, hojas, semillas y raíces. Además, se pueden encontrar en sal de apio, ensaladas, algunos productos cárnicos, sopas, salsas, etc.',
    'Además de en semillas, en polvo en forma líquida, se puede encontrar en algún tipo de panes, curry, marinados, productos cárnicos, aliños de ensalada, sopas, salsas, etc.',
    'Además de en las semillas, pastas, aceites y harinas, se puede encontrar en productos como panes, colines, bollería, etc.',
    'Se utilizan como conservantes en crustáceos, frutas desecadas, productos cárnicos, refrescos, vinagre y productos escabechados, vino y cerveza.',
    'Incluye los mejillones, almejas, caracoles de tierra, ostras, chirlas, calamares, pulpo, pota, sepia, etc.',
    'Además de en las semillas y harinas, se pueden encontrar en tipos de pan, pasteles, pasta, etc.',
]