version: "3.8"

services:
  web:
    build: ./app
    command: ../wait-for-it.sh db:5432 -t 0 --strict -- python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    env_file:
      - django.dev.env
      - postgres.dev.env
    depends_on:
      - db
  db:
    image: "postgres:13"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    env_file:
      - postgres.dev.env