version: "3.8"

services:
  nginx:
    build: ./nginx
    ports: 
      - "1700:80"
    volumes:
        - ./app/www/static:/staticfiles
        - ./app/www/media:/mediafiles
    depends_on:
      - web
  web:
    build: ./app
    command: ../wait-for-it.sh db:5432 -t 0 --strict -- sh -c "python manage.py makemigrations &&
                                                                python manage.py migrate &&
                                                                python manage.py collectstatic --noinput &&
                                                                gunicorn micartadigital.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./app:/app
    env_file:
      - django.dev.env
      - postgres.dev.env
    depends_on:
      - db
  db:
    image: "postgres:14-alpine"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    env_file:
      - postgres.dev.env
