services:
  nginx:
    build: ./nginx
    ports: 
      - "1700:80"
    volumes:
        - ./app/www/static:/staticfiles
        - ./app/www/media:/mediafiles
    depends_on:
      - web
  web:
    build: ./app
    command: "../wait-for-it.sh db:5432 -t 0 --strict -- ../start.sh"
    volumes:
      - ./app:/app
    env_file:
      - django.dev.env
      - postgres.dev.env
    depends_on:
      - db
  db:
    image: "postgres:15-alpine"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    env_file:
      - postgres.dev.env
