# Generated by Django 3.1.6 on 2021-02-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='establecimiento',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='establecimiento',
            name='email',
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='calle',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='codigo_postal',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='localidad',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='telefono',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
