# Generated by Django 3.1.6 on 2021-02-23 23:26

import cartas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartas', '0002_auto_20210221_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='establecimiento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=cartas.models.get_file_path),
        ),
    ]
