# Generated by Django 3.1.6 on 2021-02-23 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartas', '0003_establecimiento_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='establecimiento',
            name='provincia',
            field=models.CharField(default='Ourense', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='localidad',
            field=models.CharField(max_length=100),
        ),
    ]
