# Generated by Django 3.1.6 on 2021-03-10 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartas', '0005_plato_seccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='orden',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
