# Generated by Django 3.1.6 on 2021-04-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartas', '0008_plato_alergenos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
