# Generated by Django 3.1.6 on 2021-04-19 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cartas', '0011_auto_20210416_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carta',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cartas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='establecimientos', to=settings.AUTH_USER_MODEL),
        ),
    ]
