# Generated by Django 3.2 on 2021-04-20 16:49

from django.contrib.postgres.operations import TrigramExtension, UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartas', '0013_auto_20210419_2152'),
    ]

    operations = [
        TrigramExtension(),
        UnaccentExtension(),
    ]
