# Generated by Django 3.2 on 2021-04-26 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartas', '0014_auto_20210420_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='establecimiento',
            name='telefono',
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='social_fb',
            field=models.CharField(blank=True, max_length=50, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='social_ig',
            field=models.CharField(blank=True, max_length=30, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='social_tw',
            field=models.CharField(blank=True, max_length=30, verbose_name='Twitter'),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='social_wa',
            field=models.CharField(blank=True, max_length=15, verbose_name='WhatsApp'),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='telefono1',
            field=models.CharField(blank=True, max_length=15, verbose_name='teléfono principal'),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='telefono2',
            field=models.CharField(blank=True, max_length=15, verbose_name='teléfono secundario'),
        ),
    ]
