# Generated by Django 3.2 on 2021-05-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartas', '0015_auto_20210426_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establecimiento',
            name='social_wa',
            field=models.CharField(blank=True, max_length=100, verbose_name='WhatsApp'),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='telefono1',
            field=models.CharField(blank=True, max_length=18, verbose_name='teléfono principal'),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='telefono2',
            field=models.CharField(blank=True, max_length=18, verbose_name='teléfono secundario'),
        ),
    ]
